export const TEAMS = {
  atl: 'hawks',
  bkn: 'nets',
  bos: 'celtics',
  cha: 'hornets',
  chi: 'bulls',
  cle: 'cavaliers',
  dal: 'mavericks',
  den: 'nuggets',
  det: 'pistons',
  gsw: 'warriors',
  hou: 'rockets',
  ind: 'pacers',
  lac: 'clippers',
  lal: 'lakers',
  mem: 'grizzlies',
  mia: 'heat',
  mil: 'bucks',
  min: 'timberwolves',
  nop: 'pelicans',
  nyk: 'knicks',
  okc: 'thunder',
  orl: 'magic',
  phi: '76ers',
  phx: 'suns',
  por: 'trail blazers',
  sac: 'kings',
  sas: 'spurs',
  tor: 'raptors',
  uta: 'jazz',
  was: 'wizards'
}